type_dict = {
    **dict.fromkeys(["doc", "docm", "docx", "dot", "dotx", "eml", "pdf", "pot", "potm", "potx", "ppam",
                    "pps", "ppsm", "ppsx", "pptm", "ppt", "pptx", "pub", "txt", "rtf", "sldx",
                    "vsd", "vsdm", "vsdx", "vss", "vssm", "vst", "vstm", "vstx", "wbk", "xla", "xlam",
                    "xll", "xlm", "xls", "xlsm", "xlsx", "xlt", "xltm", "xltx", "xps", "asd", "bpdx",
                    "crtx", "dic", "dochtml", "docxml", "dothtml", "dqy", "epub", "exc", "fdf", "fcdt",
                    "iqy", "latex", "mobi", "odc", "odp", "ods", "odt", "one", "onepkg", "onetoc",
                    "onetoc2", "oqy", "pdx", "pothtml", "ppa", "ppthtml", "pwz", "rmf", "rqy", "sequ",
                    "sldm", "slk", "vdw", "vdx", "vsd", "vsdm", "vsdx", "vss", "vssm", "vssx",
                    "vst", "vstx", "vstm", "vtx", "vsz", "xlk", "xlsb", "xlshtml", "xlsmhtml", "xlw"], 
                    "documents"),
    **dict.fromkeys(["bmp", "gif", "jpg", "jpeg", "png", "webp", "psd", "tif", "tiff", "emf", "hdr",
                    "heic", "hif", "ico", "iff", "jfif", "jpe", "jps", "jxl", "kpp", "kra", "krz", "mdc",
                    "mrw", "mtl", "ora", "orf", "ori", "p3l", "p3m", "p3r", "pbm", "pcd", "pcx", "pdd",
                    "psb", "psdt", "psd", "psf", "pxr", "r3d", "raf", "raw", "rle", "rw2", "rwl", "rwz",
                    "shc", "shh", "srf", "sr2", "srw", "stl", "sta", "svg", "thumb", "wdp", "wmf", "x3f",
                    "xcf"], 
                    "images"),
    **dict.fromkeys(["avi", "flv", "m4a", "mkv", "mov", "mp4", "mpg", "mpeg", "vob", "wmv", "264", "bdmv",
                    "dav", "dv", "evo", "f4v", "flc", "flic", "fli", "hdmov", "h264", "ifo", "IVF", "m1v",
                    "m2p", "m2t", "m2ts", "m2v", "m4v", "mk3d", "mlp", "movie", "mp2v", "mp4v", "mpeg1",
                    "mpeg2", "mpeg4", "mpg4", "mtv", "mxf", "nuv", "ogm", "ogv", "ogx", "mpv2", "mpv4",
                    "mpls", "pva", "ram", "rec", "rm", "rmvb", "rp", "rpl", "rt", "smi", "smil", "smk",
                    "bik", "bk2", "ssif", "tp", "trp", "video", "vlc", "vob", "webm", "wmp", "wtv",
                    "xesc", "xvid"], 
                    "videos"),
    **dict.fromkeys(["aif", "aifc", "aiff", "aac", "adt", "adts", "cda", "mid", "midi", "mp3", "wav",
                    "mp4a", "wma", "ogg", "a52", "aa", "aax", "alac", "flac", "AUP", "AUP3", "cda", "cdda",
                    "flp", "fsc", "fst", "it", "ite", "itdb", "itl", "itlp", "itls", "itms", "itpc", "m3u",
                    "m3u8", "m4b", "m4p", "m4r", "mka", "mod", "mp1", "mpa", "mpc", "mpcpl", "mpd", "mpg4",
                    "mpl", "oma", "opus", "pls", "qcp", "ra", "rmi", "rmp", "s3m", "snd", "spx", "tta", 
                    "vro", "voc", "vqf", "w64", "wave", "wax", "wm", "WMD", "wmdb", "wmx", "wpl", "xa", 
                    "xm"], 
                    "audio"),
    **dict.fromkeys(["iso", "jar", "rar", "zip", "7z", "gz", "lha", "lz", "lzh", "rev", "tar", "taz",
                    "tbz", "tbz2", "tgz", "tlz", "txz", "tzst", "uu", "uue", "xxe", "xz", "z", "zipx"], 
                    "archives"),
    **dict.fromkeys(["exe", "msi", "swf", "appinstaller", "appx", "application", "appxbundle", "com",
                   "ipa", "ipg", "ipsw", "msu", "msix", "msixbundle", "msp", "opc"], 
                    "software"),
    **dict.fromkeys(["accdb", "accde", "accdr", "accdt", "db", "bin", "aspx", "csv", "ini", "mdb", "pst",
                    "cfg", "config", "dat", "data", "dmp", "fbx", "obj", "glb", "gltf", "inf",
                    "info", "label", "log", "nfo", "ply", "sql", "UDL", "xdp", "xdr", "xml", "json", 
                    "jsonld"], 
                    "data"),
    **dict.fromkeys(["bat", "api", "bash", "bashrc", "bash_login", "bash_logout", "cls", "cmake", "dsp",
                    "bash_profile", "c", "c++", "cc", "cpp", "cppm", "cs", "def", "diff", "git", "erb",
                    "fs", "fsi", "fsscript", "fx", "gitattributes", "gitconfig", "gitignore", "gitmodules",
                    "gradle", "groovy", "h", "hh", "h++", "hpp", "hs", "hxx", "i", "idl", "inc", "inl",
                    "ipp", "ipynb", "jade", "jav", "java", "ixx", "itrace", "js", "jscsrc", "JSE", 
                    "jshintrc", "jshtml", "jsp", "jsproj", "jsx", "mak", "makefile",
                    "manifest", "man", "md", "mdoc", "mdown", "mdp", "mdtext", "mdtxt", "mdwn", "mjs", "mk",
                    "mkd", "mkdn", "ml", "mlc", "mtx", "npmignore", "odh", "odl", "package", "php", "phtml",
                    "pl", "pkgdef", "pkgundef", "plist", "pl6", "pp", "profile", "properties", "project",
                    "ps1", "ps1xml", "props", "psgi", "psd1", "psc1", "publishproj", "pubxml", "py", "pyc",
                    "pyd", "pydevproject", "pyi", "pyo", "pyproj", "pyw", "pyz", "pyzw", "r", "rb", "rc",
                    "rc2", "rct", "rgs", "rs", "rst", "ruleset", "s", "sass", "sh", "sln", "slnf",
                    "snippet", "spdata", "sqlproj", "t", "targets", "tex", "tlh", "tli", "toml", "tsx",
                    "unity", "unityhub", "unityPackage", "vb", "vbe", "vbproj", "vcp", "vcproj", "vcw",
                    "vcxitems", "vcxproj", "wsdl", "zsh", "xcodeproj", "unreal"], 
                    "code"),
    **dict.fromkeys(["htm", "html", "chm", "css", "hta", "mht", "mhtml", "shtm", "shtml", "URL",
                     "website", "xht", "xhtml"], 
                    "web"),
    **dict.fromkeys(["dll", "sys", "blg", "cpl", "gmmp", "icc", "reg", "wsc", "WSH", "WSF"], 
                    "utilities"),
    **dict.fromkeys(["fon", "fnt", "otf", "pfm", "ttc", "ttf", "woff", "woff2", "eot", "fot"], 
                    "fonts"),
    **dict.fromkeys(["apkg", "anki", "anki2", "anki21", "apkg2", "media"], 
                    "anki"),
    **dict.fromkeys(["vbox", "temp", "tmp"], 
                    "other")
    }